# 默认使用的环境
env: test

test: # 测试环境
  base_url: ${APEX_OMNI_HTTP_TEST} # 测试环境地址
  network_id: ${NETWORKID_TEST}
prod: # 生产环境
  base_url: ${APEX_OMNI_HTTP_MAIN} # 生产环境地址
  network_id: ${NETWORKID_MAIN}
# 测试报告配置
report:
  title: "Apex API 自动化测试报告"
  description: "API自动化测试报告"
  language: zh-CN